# Generated by Django 4.1.6 on 2023-02-08 14:07

from django.db import migrations, models
import django.db.models.deletion
import ledger.models.ledger_model
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('COMMON', 'Common'), ('SPECIAL', 'Special')], default='COMMON', max_length=7)),
                ('amount', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('client_id', 'account_type', 'amount')},
            },
        ),
        migrations.CreateModel(
            name='LedgerModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ledger_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('amount', ledger.models.ledger_model.MinMaxFloat()),
                ('description', models.TextField(blank=True, default='No Description')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.accountmodel')),
            ],
        ),
    ]
